// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2129.swRobotics2016b.subsystems;

import org.usfirst.frc2129.swRobotics2016b.RobotMap;

import edu.wpi.first.wpilibj.Preferences;
import edu.wpi.first.wpilibj.Servo;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;



/**
 *
 */
public class Shooter extends Subsystem {

	private double spinSpeed;
	
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController spinnerLeftController = RobotMap.shooterspinnerLeftController;
    private final SpeedController spinnerRightController = RobotMap.shooterspinnerRightController;
    private final Servo ballPusherServo = RobotMap.shooterballPusherServo;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    public void spinForIntake() {
    	//spinSpeed = Robot.preferences
    	spinSpeed = Preferences.getInstance().getDouble("intakeSpinSpeed", .1);
    	spinnerLeftController.set(spinSpeed);
    	spinnerRightController.set(spinSpeed*-1);
    }
    
    public void spinForShooting() {
    	//spinSpeed = Robot.preferences
    	spinSpeed = Preferences.getInstance().getDouble("shootSpinSpeed", .35);
    	spinnerLeftController.set(spinSpeed*-1);
    	spinnerRightController.set(spinSpeed);
    }
    
    public void stopSpinning() {
    	spinnerLeftController.set(0);
    	spinnerRightController.set(0);
    }

}

