// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2129.swRobotics2016b.subsystems;

import org.usfirst.frc2129.swRobotics2016b.Robot;
import org.usfirst.frc2129.swRobotics2016b.RobotMap;
import edu.wpi.first.wpilibj.SpeedController;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Shooter_Spinners extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController leftController = RobotMap.shooter_SpinnersLeftController;
    private final SpeedController rightController = RobotMap.shooter_SpinnersRightController;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public void spinForIntake() {
    	//spinSpeed = Robot.preferences
    	double spinSpeed = Robot.preferences.getDouble("intakeSpinSpeed", .1);
    	leftController.set(spinSpeed);
    	rightController.set(spinSpeed * -1.0);
    }
    
    public void spinForShooting() {
    	//spinSpeed = Robot.preferences
    	double spinSpeed = Robot.preferences.getDouble("shootSpinSpeed", .75);
    	leftController.set(spinSpeed * -1.0);
    	rightController.set(spinSpeed);
    }
    
    public void stopSpinning() {
    	leftController.set(0);
    	rightController.set(0);
    }

}

