// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2129.swRobotics2016b.commands;

import org.usfirst.frc2129.swRobotics2016b.Robot;

import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;

/**
 *
 */
public class moveBallPusherToLaunch extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public moveBallPusherToLaunch() {
    	sweepDelayTimer = new Timer();
    	
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.shooter);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	hasStarted = false;
    	isInterrupted = false;
    	ballPusherSweepDelaySeconds = Robot.preferences.getLong("ballPusherSweepDelaySeconds",  2);
    	
    }

    private boolean hasStarted;
    private boolean isInterrupted;
    private long ballPusherSweepDelaySeconds;
    private Timer sweepDelayTimer;
    
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
		Robot.shooter.pushBallIntoFiringPath();

    	if (!hasStarted)
    	{
    		hasStarted = true;
    		sweepDelayTimer.start();
    	}
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	if (isInterrupted)
    	{
    		return true;
    	}
    	double sweepDelayTimerValue = sweepDelayTimer.get();
    	
    	if (hasStarted &&  sweepDelayTimerValue >= ballPusherSweepDelaySeconds)
    	{
    		return true;
    	}
    	
    	return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	isInterrupted = true;
    }
}
