// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2129.swRobotics2016b;

import org.usfirst.frc2129.swRobotics2016b.commands.AutonomousCommand;
import org.usfirst.frc2129.swRobotics2016b.commands.DriveCommand;
import org.usfirst.frc2129.swRobotics2016b.commands.intakeLifter;
import org.usfirst.frc2129.swRobotics2016b.commands.intakeRoller;
import org.usfirst.frc2129.swRobotics2016b.commands.moveBallPusherForIntake;
import org.usfirst.frc2129.swRobotics2016b.commands.moveBallPusherToLaunch;
import org.usfirst.frc2129.swRobotics2016b.commands.pickUpBall;
import org.usfirst.frc2129.swRobotics2016b.commands.shooterLifter;
import org.usfirst.frc2129.swRobotics2016b.commands.spinShooterWheelsForIntake;
import org.usfirst.frc2129.swRobotics2016b.commands.spinShooterWheelsForLaunch;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
import edu.wpi.first.wpilibj.command.Scheduler;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    
    
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton intakeUp;
    public JoystickButton intakeDown;
    public JoystickButton intakeIn;
    public JoystickButton intakeOut;
    public JoystickButton joystickButton1;
    public Joystick leftJoystick;
    public JoystickButton shooterUp;
    public JoystickButton shooterDown;
    public JoystickButton shooterIn;
    public JoystickButton shooterOut;
    public JoystickButton shooterFire;
    public JoystickButton shooterAutoAim;
    public JoystickButton shooterCalibrate;
    public Joystick rightJoystick;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
    	System.out.println("swRobotics2016b swRobotics2016b swRobotics2016b swRobotics2016b swRobotics2016b swRobotics2016b swRobotics2016b swRobotics2016b");
    	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        rightJoystick = new Joystick(1);
        
        shooterCalibrate = new JoystickButton(rightJoystick, 11);
        shooterCalibrate.whileHeld(new shooterLifter());
        shooterAutoAim = new JoystickButton(rightJoystick, 2);
        shooterAutoAim.whileHeld(new shooterLifter());
        shooterFire = new JoystickButton(rightJoystick, 1);
        shooterFire.whileHeld(new spinShooterWheelsForLaunch());
        shooterOut = new JoystickButton(rightJoystick, 6);
        shooterOut.whileHeld(new spinShooterWheelsForLaunch());
        shooterIn = new JoystickButton(rightJoystick, 4);
        shooterIn.whileHeld(new spinShooterWheelsForIntake());
        shooterDown = new JoystickButton(rightJoystick, 5);
        shooterDown.whileHeld(new shooterLifter());
        shooterUp = new JoystickButton(rightJoystick, 3);
        shooterUp.whileHeld(new shooterLifter());
        leftJoystick = new Joystick(0);
        
        joystickButton1 = new JoystickButton(leftJoystick, 1);
        joystickButton1.whenPressed(new pickUpBall());
        intakeOut = new JoystickButton(leftJoystick, 5);
        intakeOut.whileHeld(new intakeRoller());
        intakeIn = new JoystickButton(leftJoystick, 4);
        intakeIn.whileHeld(new intakeRoller());
        intakeDown = new JoystickButton(leftJoystick, 3);
        intakeDown.whileHeld(new intakeLifter());
        intakeUp = new JoystickButton(leftJoystick, 2);
        intakeUp.whileHeld(new intakeLifter());


        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("DriveCommand", new DriveCommand());
        SmartDashboard.putData("intakeRoller", new intakeRoller());
        SmartDashboard.putData("intakeLifter", new intakeLifter());
        SmartDashboard.putData("spinShooterWheelsForLaunch", new spinShooterWheelsForLaunch());
        SmartDashboard.putData("spinShooterWheelsForIntake", new spinShooterWheelsForIntake());
        SmartDashboard.putData("shooterLifter", new shooterLifter());
        SmartDashboard.putData("moveBallPusherToLaunch", new moveBallPusherToLaunch());
        SmartDashboard.putData("moveBallPusherForIntake", new moveBallPusherForIntake());
        SmartDashboard.putData("pickUpBall", new pickUpBall());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    
    SmartDashboard.putData(Scheduler.getInstance());
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getleftJoystick() {
        return leftJoystick;
    }

    public Joystick getrightJoystick() {
        return rightJoystick;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

