// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2129.swRobotics2016b;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.Jaguar;
import edu.wpi.first.wpilibj.PowerDistributionPanel;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Servo;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveleft1;
    public static SpeedController driveleft2;
    public static SpeedController driveright1;
    public static SpeedController driveright2;
    public static RobotDrive drivetankDrive;
    public static SpeedController shooter_SpinnersLeftController;
    public static SpeedController shooter_SpinnersRightController;
    public static CANTalon intakeintakeMotor;
    public static PowerDistributionPanel powerDistributionpowerDistributionPanel;
    public static Servo shooter_BallPusherServo;
    public static CANTalon elevatorElevatorDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveleft1 = new Talon(0);
        LiveWindow.addActuator("Drive", "left1", (Talon) driveleft1);
        
        driveleft2 = new Talon(19);
        LiveWindow.addActuator("Drive", "left2", (Talon) driveleft2);
        
        driveright1 = new Talon(2);
        LiveWindow.addActuator("Drive", "right1", (Talon) driveright1);
        
        driveright2 = new Talon(14);
        LiveWindow.addActuator("Drive", "right2", (Talon) driveright2);
        
        drivetankDrive = new RobotDrive(driveleft1, driveleft2,
              driveright1, driveright2);
        
        drivetankDrive.setSafetyEnabled(true);
        drivetankDrive.setExpiration(0.1);
        drivetankDrive.setSensitivity(0.5);
        drivetankDrive.setMaxOutput(1.0);

        drivetankDrive.setInvertedMotor(RobotDrive.MotorType.kRearLeft, true);
        drivetankDrive.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);
        shooter_SpinnersLeftController = new Jaguar(1);
        LiveWindow.addActuator("Shooter_Spinners", "LeftController", (Jaguar) shooter_SpinnersLeftController);
        
        shooter_SpinnersRightController = new Jaguar(3);
        LiveWindow.addActuator("Shooter_Spinners", "RightController", (Jaguar) shooter_SpinnersRightController);
        
        intakeintakeMotor = new CANTalon(6);
        LiveWindow.addActuator("Intake", "intakeMotor", intakeintakeMotor);
        
        powerDistributionpowerDistributionPanel = new PowerDistributionPanel(0);
        LiveWindow.addSensor("PowerDistribution", "powerDistributionPanel", powerDistributionpowerDistributionPanel);
        
        shooter_BallPusherServo = new Servo(4);
        LiveWindow.addActuator("Shooter_BallPusher", "Servo", shooter_BallPusherServo);
        
        elevatorElevatorDrive = new CANTalon(5);
        LiveWindow.addActuator("Elevator", "ElevatorDrive", elevatorElevatorDrive);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        ((Jaguar)shooter_SpinnersRightController).enableDeadbandElimination(true);
        ((Jaguar)shooter_SpinnersLeftController).enableDeadbandElimination(true);
    }
}
